name: TableGamesPlugin
version: '${version}'

main: net.dvmn2.tablegamesplugin.TableGamesPlugin
api-version: '1.21.11'
load: POSTWORLD

authors: [ DVMN2 ]

permissions:
  tablegames.give:
    description: Allows giving a brand-new deck of playing cards.
    default: op